// <auto-generated />
using System;
using ABCReportingSystem.BranchOffice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABCReportingSystem.BranchOffice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210905053043_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ABCReportingSystem.BranchOffice.Models.Automobile", b =>
                {
                    b.Property<Guid>("AutomobileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("AutomobileId");

                    b.ToTable("Automobiles");

                    b.HasData(
                        new
                        {
                            AutomobileId = new Guid("65a1e10e-68ad-4ddc-b92c-32d36cf45cee"),
                            BranchOfficeId = -1,
                            Make = "Tesla",
                            Model = "Model S",
                            Year = 2021
                        },
                        new
                        {
                            AutomobileId = new Guid("1f8267e5-78f1-49ed-8476-823d4d439352"),
                            BranchOfficeId = -2,
                            Make = "Toyota",
                            Model = "RAV4",
                            Year = 2021
                        },
                        new
                        {
                            AutomobileId = new Guid("ccd557c5-877f-482f-bca1-722d5198b0a9"),
                            BranchOfficeId = -3,
                            Make = "Hyundai",
                            Model = "KONA",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("ABCReportingSystem.BranchOffice.Models.BranchOffice", b =>
                {
                    b.Property<int>("BranchOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchOfficeCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchOfficeState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchOfficeId");

                    b.ToTable("BranchOffices");

                    b.HasData(
                        new
                        {
                            BranchOfficeId = -1,
                            BranchOfficeCountry = "US",
                            BranchOfficeState = "California"
                        },
                        new
                        {
                            BranchOfficeId = -2,
                            BranchOfficeCountry = "US",
                            BranchOfficeState = "New York"
                        },
                        new
                        {
                            BranchOfficeId = -3,
                            BranchOfficeCountry = "US",
                            BranchOfficeState = "Massachusetts"
                        });
                });

            modelBuilder.Entity("ABCReportingSystem.BranchOffice.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("fb0f1585-cb42-4f01-a25d-6e441b414f72"),
                            BranchOfficeId = -1,
                            FirstName = "Dio",
                            LastName = "Brando",
                            Username = "diobrando1"
                        },
                        new
                        {
                            EmployeeId = new Guid("189a302d-1aa7-4110-a43d-833183446a4b"),
                            BranchOfficeId = -2,
                            FirstName = "Jolyne",
                            LastName = "Cujoh",
                            Username = "jolynecujoh"
                        },
                        new
                        {
                            EmployeeId = new Guid("f3022c0b-d875-45a1-9c36-bec333877595"),
                            BranchOfficeId = -3,
                            FirstName = "Gyro",
                            LastName = "Zepelli",
                            Username = "gzepelli"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
